:description: This section describes the different deployment modes of ONgDB Browser.


[[deployment-modes]]
= Deployment modes

There are several different scenarios of how to run ONgDB Browser:

* ONgDB Server -- ONgDB includes an HTTP server that can host the `BROWSER` module (ONgDB Browser).
* ONgDB Desktop -- ONgDB Browser comes out-of-the-box when you install ONgDB Desktop on your system.
* Web application -- ONgDB Browser is available as a web application, (link:https://browser.graphapp.io/[Go to Web application^]).
* ONgDB Sandbox -- Try out ONgDB and ONgDB Browser. (link:https://ongdb.com/sandbox/[Go to ONgDB Sandbox^]).
* ONgDB Cloud -- ONgDB Browser is available from the ONgDB Cloud console. (link:https://cloud.ongdb.com[Go to ONgDB Cloud^]).
* Dedicated web server -- Host ONgDB Browser as a standalone HTTP web application.


ONgDB Browser is open source (GNU General Public License v3.0) and the source code can be found at link:https://github.com/graphfoundation/ongdb-browser[_https://github.com/graphfoundation/ongdb-browser_^].

**The following web browsers are supported:**

* Chrome (Latest version)
* Firefox (Latest version)
* Edge (Latest version)

[WARNING]
====
Internet Explorer is not supported.
====

[TIP]
====
For details on how to set up a connection to ONgDB in ONgDB Browser, see xref:operations/dbms-connection.adoc[].
====

