:description: This section describes the different deployment modes of ONgDB Browser.


[[deployment-modes]]
= Deployment modes

There are several different scenarios of how to run ONgDB Browser:

* Neo4j Server -- Neo4j includes an HTTP server that can host the `BROWSER` module (ONgDB Browser).
* Neo4j Desktop -- ONgDB Browser comes out-of-the-box when you install Neo4j Desktop on your system.
* Web application -- ONgDB Browser is available as a web application, (link:https://browser.graphapp.io/[Go to Web application^]).
* Neo4j Sandbox -- Try out Neo4j and ONgDB Browser. (link:https://neo4j.com/sandbox/[Go to Neo4j Sandbox^]).
* Neo4j Aura -- ONgDB Browser is available from the Neo4j Aura console. (link:https://console.neo4j.io[Go to Neo4j Aura^]).
* Dedicated web server -- Host ONgDB Browser as a standalone HTTP web application.


ONgDB Browser is open source (GNU General Public License v3.0) and the source code can be found at link:https://github.com/graphfoundation/ongdb-browser[_https://github.com/neo4j/neo4j-browser_^].

**The following web browsers are supported:**

* Chrome (Latest version)
* Firefox (Latest version)
* Edge (Latest version)

[WARNING]
====
Internet Explorer is not supported.
====

[TIP]
====
For details on how to set up a connection to ONgDB in ONgDB Browser, see xref:operations/dbms-connection.adoc[].
====

